M48
; DRILL file KiCad 10.0.0-rc1.1-4-gef7340bffd date 2026-03-04T22:26:53
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-04T22:26:53+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0-rc1.1-4-gef7340bffd
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X151.034Y-71.333
X156.814Y-71.333
T2
X112.5Y-73.0
X112.5Y-125.0
X154.5Y-84.5
X154.5Y-125.0
M30
